### ISSUE TITLE
Reply UI bug

### ISSUE THREAD

**Issue by mohsinalimat** [realpaliy/mChat#4]
Hello,

replay UI bug when user name is long and text message is sort.

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-12 at 09 32 43](https://user-images.githubusercontent.com/973676/76486223-bb3b4980-6444-11ea-8048-8918f97ed8be.png)

**Comment by realpaliy** [comment]
Hi,
I have fixed this issue in the 1.2.1 update.
